import { useCallback, useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import Header from '../components/layout/Header';
import { attendanceService } from '../services/attendanceService';
import { authService } from '../services/authService';
export default function Operator() {
  const [sessions, setSessions] = useState([]); const [users, setUsers] = useState([]); const [userId, setUserId] = useState(''); const [message, setMessage] = useState('');
  const load = useCallback(async () => { const [s, u] = await Promise.all([attendanceService.getOpenSessions(), authService.getUsers()]); setSessions(s.sessions || []); setUsers((u.users || []).filter((x) => x.status === 'ACTIVE')); }, []);
  useEffect(() => { load().catch((e) => setMessage(e.message)); }, [load]);
  const manual = async (session) => { try { await attendanceService.recordManual({ eventId: session.eventId, sessionId: session.id, userId: Number(userId) }); setMessage('Manual attendance recorded.'); } catch (e) { setMessage(e.message); } };
  const close = async (session) => { try { await attendanceService.closeSession(session.id); setMessage('Session closed.'); await load(); } catch (e) { setMessage(e.message); } };
  return <div className="min-h-screen bg-slate-950 text-white"><Header /><main className="mx-auto max-w-5xl p-4 sm:p-8"><div className="flex flex-wrap justify-between gap-3"><div><h1 className="text-3xl font-bold">Attendance operations</h1><p className="mt-1 text-slate-400">Select an open session, then scan a card or record a manual check-in.</p></div><Link to="/operator/benchmark" className="min-h-11 rounded-lg border border-slate-700 px-4 py-3 text-sm">Open benchmark</Link></div>{message && <div role="status" className="my-4 rounded-lg border border-blue-500/30 bg-blue-500/10 p-3">{message}</div>}<div className="mt-6 grid gap-4">{sessions.map((session) => <article key={session.id} className="rounded-xl border border-slate-800 bg-slate-900 p-5"><h2 className="font-bold">{session.event?.name}</h2><p className="text-xs text-emerald-400">OPEN since {new Date(session.openedAt).toLocaleString()}</p><div className="mt-4 flex flex-col gap-3 sm:flex-row"><Link state={{ session }} to="/operator/nfc-reader" className="min-h-11 rounded-lg bg-emerald-600 px-4 py-3 text-center text-sm font-semibold">Use NFC scanner</Link><select aria-label="Member for manual attendance" value={userId} onChange={(e) => setUserId(e.target.value)} className="min-h-11 rounded-lg border border-slate-700 bg-slate-950 px-3"><option value="">Select member</option>{users.map((u) => <option key={u.id} value={u.id}>{u.firstName} {u.lastName}</option>)}</select><button disabled={!userId} onClick={() => manual(session)} className="min-h-11 rounded-lg bg-blue-600 px-4 text-sm disabled:opacity-50">Record manual</button><button onClick={() => close(session)} className="min-h-11 rounded-lg border border-rose-500/40 px-4 text-sm text-rose-300">Close session</button></div></article>)}{!sessions.length && <p className="text-slate-400">No open attendance sessions.</p>}</div></main></div>;
}
